services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lodus
    ports:
      - "5432:5432"
    volumes:
      - lodus_pg_data:/var/lib/postgresql/data

volumes:
  lodus_pg_data:
